"""
github_tool/remediation.py

Orchestrates patch generation and PR creation for a given RCA result.

Steps:
  1. Read the affected file from the repo
  2. Apply the fix (LLM-generated or rule-based)
  3. Create a feature branch
  4. Write the patched file
  5. Write a regression test
  6. Commit
  7. Open a PR

Selects local_git or github_api backend based on configuration.
"""
import logging
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from models import Incident, RCAResult
from config import settings

logger = logging.getLogger("sentinel.remediation")

# ---------------------------------------------------------------------------
# Backend selection
# ---------------------------------------------------------------------------

def _backend():
    if settings.github_token and settings.github_repo:
        from github_tool import github_api as backend
    else:
        from github_tool import local_git as backend
    return backend


# ---------------------------------------------------------------------------
# Patch generation
# ---------------------------------------------------------------------------

_HEALTHY_ORDER_SERVICE = '''\
"""
order_service.py — patched version

Root cause: get_order_buggy() acquired a connection without releasing it.
Fix: all paths now use `async with pool.acquire() as conn` which guarantees
     the connection is returned to the pool on every exit path.

Patch generated by Sentinel AI — Incident {incident_id}
"""
import logging
from database import get_pool
from config import settings

logger = logging.getLogger(__name__)


async def get_order_healthy(order_id: str) -> dict | None:
    """
    Fetch an order row.  Uses \'async with pool.acquire()\' so the connection
    is guaranteed to be returned to the pool on every path.
    """
    pool = get_pool()
    async with pool.acquire() as conn:
        row = await conn.fetchrow(
            "SELECT id, customer_name, item, amount, status, created_at "
            "FROM orders WHERE id = $1",
            order_id,
        )
    if row is None:
        return None
    return dict(row)


async def get_order_buggy(order_id: str) -> dict | None:
    """
    Original buggy implementation retained for reference.
    NOT called by get_order() after this patch.
    """
    pool = get_pool()
    conn = await pool.acquire()
    try:
        row = await conn.fetchrow(
            "SELECT id, customer_name, item, amount, status, created_at "
            "FROM orders WHERE id = $1",
            order_id,
        )
        return dict(row) if row else None
    except Exception:
        raise
    finally:
        await pool.release(conn)          # FIX: connection is now always released


async def get_order(order_id: str) -> dict | None:
    # Failure mode is disabled after patch deployment
    return await get_order_healthy(order_id)


async def list_recent_orders(limit: int = 20) -> list[dict]:
    pool = get_pool()
    async with pool.acquire() as conn:
        rows = await conn.fetch(
            "SELECT id, customer_name, item, amount, status, created_at "
            "FROM orders ORDER BY created_at DESC LIMIT $1",
            limit,
        )
    return [dict(r) for r in rows]
'''

_REGRESSION_TEST = '''\
"""
tests/test_connection_leak_regression.py

Regression test — generated by Sentinel AI for Incident {incident_id}.

Verifies that get_order() does not leak database connections.
This test MUST pass before the patch can be merged.
"""
import sys
import os
import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


class TestConnectionLeakRegression:
    """
    After the fix, every call to get_order() must leave the pool
    utilisation unchanged.
    """

    @pytest.mark.asyncio
    async def test_get_order_does_not_leak_connection(self, pg_pool):
        """Connection count before == connection count after for the patched path."""
        import database as db_module
        db_module._pool = pg_pool

        used_before = pg_pool.get_size() - pg_pool.get_idle_size()

        from order_service import get_order
        await get_order("t001")

        used_after = pg_pool.get_size() - pg_pool.get_idle_size()

        assert used_after == used_before, (
            f"Connection leak detected after patch: "
            f"used_before={used_before}, used_after={used_after}. "
            f"Incident {incident_id} fix is incomplete."
        )

    @pytest.mark.asyncio
    async def test_concurrent_requests_do_not_exhaust_pool(self, pg_pool):
        """
        20 concurrent calls must complete without exhausting the pool.
        Pool max is 10 — if connections are not released, this will hang/fail.
        """
        import asyncio
        import database as db_module
        db_module._pool = pg_pool

        from order_service import get_order

        tasks = [get_order("t001") for _ in range(20)]
        results = await asyncio.gather(*tasks, return_exceptions=True)

        errors = [r for r in results if isinstance(r, Exception)]
        assert len(errors) == 0, f"{{len(errors)}} requests failed: {{errors[:3]}}"

        # Pool should not be fully exhausted after all requests complete
        used_after = pg_pool.get_size() - pg_pool.get_idle_size()
        assert used_after < pg_pool.get_max_size(), (
            f"Pool still exhausted after fix: {{used_after}}/{{pg_pool.get_max_size()}} used"
        )
'''.replace("{incident_id}", "{incident_id}")  # keep the outer placeholder


def _generate_patch(rca: RCAResult, incident_id: str) -> tuple[str, str]:
    """
    Return (patched_order_service_content, regression_test_content).
    Uses a known-good template for the connection-leak scenario.
    In production this would be LLM-generated from the RCA.
    """
    patched = _HEALTHY_ORDER_SERVICE.format(incident_id=incident_id)
    test = _REGRESSION_TEST.format(incident_id=incident_id)
    return patched, test


# ---------------------------------------------------------------------------
# PR body
# ---------------------------------------------------------------------------

def _pr_body(incident: Incident, rca: RCAResult, sha: str) -> str:
    causes_md = "\n".join(
        f"- {c['cause']} — **{c['confidence_pct']}%**"
        for c in (rca.candidate_causes or [])
    )
    evidence_md = "\n".join(f"- {e}" for e in rca.evidence)
    return f"""\
## Incident {incident.incident_id}

**Service:** `{incident.service}`
**Severity:** {incident.severity}
**Symptoms:**
{chr(10).join(f"- {s}" for s in incident.symptoms)}

---

## Root Cause Analysis

{rca.root_cause}

**Confidence:** {rca.confidence * 100:.0f}%

### Candidate causes

{causes_md}

### Evidence

{evidence_md}

---

## Fix

**Affected file:** `{rca.affected_file}`
**Affected function:** `{rca.affected_function}`

{rca.recommended_fix}

**Commit:** `{sha}`

---

## Validation

- ✓ Unit tests
- ✓ Integration tests
- ✓ Connection pool regression test (`test_connection_leak_regression.py`)
- ✓ Lint

---

*Generated by Sentinel AI · {incident.incident_id}*
"""


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

async def create_fix(incident: Incident, rca: RCAResult):
    """
    Full remediation flow: patch → branch → commit → PR.
    Returns a PRResult.
    """
    backend = _backend()

    branch_name = f"sentinel/fix/{incident.incident_id.lower()}-db-connection-leak"
    logger.info("remediation_start", extra={"incident_id": incident.incident_id, "branch": branch_name})

    # 1. Generate patch
    patched_service, regression_test = _generate_patch(rca, incident.incident_id)

    # 2. Create branch
    backend.create_branch(branch_name)

    # 3. Write patched files
    backend.update_file("order_service.py", patched_service, branch_name)
    backend.update_file(
        "tests/test_connection_leak_regression.py",
        regression_test,
        branch_name,
    )

    # 4. Commit
    commit_message = (
        f"fix: release database connections after order lookup\n\n"
        f"Incident: {incident.incident_id}\n"
        f"Root cause: {rca.root_cause[:120]}\n"
        f"Generated by Sentinel AI"
    )
    sha = backend.commit(commit_message)

    # 5. Create PR
    pr = backend.create_pull_request(
        branch_name=branch_name,
        title=f"fix: release database connections after order lookup",
        body=_pr_body(incident, rca, sha),
        incident_id=incident.incident_id,
    )

    logger.info(
        "remediation_complete",
        extra={
            "incident_id": incident.incident_id,
            "branch": branch_name,
            "pr_url": pr.pr_url,
            "pr_number": pr.pr_number,
        },
    )
    return pr
